name: Print Image Tags

on:
  workflow_dispatch:
    inputs:
      APP_TAG_FOO:
        description: 'App tag foo'
        required: false
        type: string
      APP_TAG_BAR:
        description: 'App tag bar'
        required: false
        type: string

jobs:
  print-tags:
    runs-on: ubuntu-latest
    env:
      APP_TAG_FOO: ${{ inputs.APP_TAG_FOO }}
      APP_TAG_BAR: ${{ inputs.APP_TAG_BAR }}
    steps:
      - name: Print image tags
        run: |
          echo "APP_TAG_FOO: ${APP_TAG_FOO:-none}"
          echo "APP_TAG_BAR: ${APP_TAG_BAR:-none}"
